export const data = {
  first: {
    cse: [
      'Engineering Mathematics-I/Engineering Mathematics-II',
      'Computer Programming',
      'Engineering Graphics',
      'Engineering Physics',
      'Applied Mechanics',
      'Basic Electronics Engineering',
      'Communication Skills',
      'Engineering Workshop',
      'Engineering Chemistry',
      'Materials Science & Engineering',
      'Basic Electrical Engineering',
    ],
  },

  second: {
    cse: [
      'Engineering mathematics-III',
      'Object Oriented Programming',
      'Microprocessor and Interfacing',
      'Discrete Structures',
      'Digital Electronincs and Logic Design',
      'Organizational Behaviour',
      'Data Strutures',
      'Computer Organization and Architecture',
      'Operating System',
      'Theory of Computation',
    ],
    ece: [
      'Organizational Behaviour',
      'Digital Electronics and Logic Design',
      'Analog Electronics',
      'Communication Theory',
      'Data Structures',
      'Engineering Mathematics-III',
      'Linear Integrated Circuits',
      'Analog Communucation Systems',
      'Electromagnetic Field Theory',
      'VLSI Technology',
    ],
    ee: [
      'Engineering mathematics-III',
      'Network Analysis and Synthesis',
      'Electromagnetic Field Theory',
      'Electrical and Elecrtonic Measurements',
      'Digital Electronics and Logic Design',
      'Organizational Bhaviour',
      'Electrical Machines-I',
      'Microprocessor Architecture and Interfacing',
      'Power electronics',
      'Power System',
    ],
    ce: [
      'Engineering Mathematics-III',
      'Determinate Structures',
      'Fluid Mechanics',
      'Engineering Geology and Rock Mechanics',
      'Surveying',
      'Organizational Behaviour',
      'Indeterminate Structures',
      'Water Resource Engineering-I',
      'Soil Mechanics',
      'Building Materials and Construction',
    ],
    ch: [
      'Organizational Behaviour',
      'Fluid Mechanics',
      'Chemical Engineering Thermodynamics-I',
      'Chemical Process Calculations',
      'Mechanical Operation',
      'Engineering Mathematics-III',
      'Heat Transfer',
      'Chemical Engineering Thermodynamics-II',
      'Industrial Pollution Abatement',
      'Chemical Technology',
    ],

    me: [
      'Organization Behavior',
      'Kinetics of Machines',
      'Engineering Thermodynamics',
      'Fluid Mechanics and Machinery',
      'Metrology and Measurement',
      'Engineering Mathematics-III',
      'Dynamics of Machines',
      'Heat and Mass Transfer',
      'Mechanics of Solids',
      'Industrial Engineering',
    ],
    ms: [
      'Organizational Behavior',
      'Phase Transformation',
      'Transport Phenomena',
      'Materials Thermodynamics and Kinetics',
      'Mechanical Behavior of Materials',
      'Engineering Mathematics-III',
      'Heat Treatment',
      'Polymer Science and Technology',
      'Composite Materials',
      'Materials Processing Techniques',
    ],
    ma: [
      'Engineering Mathematics-III',
      'Discrete Mathematics',
      'Stochastic Processes',
      'Computer Graphics',
      'Object Oriented Programming',
      'Organizational Behaviour',
      'Linear Algebra and Applications',
      'Statistical Methods',
      'Data Structure',
      'Operating System',
    ],
  },

  third: {
    cse: [
      'Analysis and Designs of Algorithms',
      'Database Management Systems',
      'Compiler Design',
      'Computer Graphics',
      'Distributed Systems',
      'Software Engineering',
      'Digital Image Processing',
      'Computer Networks',
    ],
    ece: [
      'Microprocessor Arhitecture and Applications',
      'Digital Communication and Systems',
      'Digital Signal processing',
      'Microware Devices and Systems',
      'Microcontroller and Embedded Systems',
      'Wireless Communication',
      'VLSI Design Techniques',
      'Antenna and Wave propagation',
    ],
    ee: [
      'Protection and Switchgear',
      'Electrical Machines-II',
      'Signals and Systems',
      'Transducers and Signal Conditioning',
      'Control Engineering',
      'Power System Analysis',
      'Digital Signal Processing',
      'Electric Drives',
    ],
    ce: [
      'RCC Design',
      'Water Supply and Treatment',
      'Foundation Engineering',
      'Highway Engineering',
      'Steel Structure',
      'Water Resources Engineering-II',
      'Railways and Airports',
      'Waste Water Treatment and Management',
    ],
    ch: [
      'Mass Transfer-I',
      'Chemical Reaction Engineering-I',
      'Process Equipment Design-I',
      'Process Dynamics and Control',
      'Mass Transfer-II',
      'Chemical Reaction Engineering-II',
      'Process Equipment Design-II',
      'Process Modeling and Simulation',
    ],
    me: [
      'Machine Design-I',
      'Manufacturing Science and Technology-I',
      'Thermal Power Engineering-I',
      'Refrigeration and Air Conditioning',
      'Machine Design-II',
      'Manufacturing Science and Technology-II',
      'Thermal Power Engineering-II',
      'Automobile Engineering',
    ],
    ms: [
      'Characterization of Materials',
      'Ceramics Science and Engineering',
      'Iron and Steel Making',
      'Metal working Science & Technology',
      'Non-Destructive Testing of Materials',
      'Tribology of Engineering Materials',
      'Non-Ferrous Extractive Metallurgy',
      'Computational Materials Science',
    ],
    ma: [
      'Operation Research',
      'Number Theory and Abstract Algebra',
      'Data Base Management Systems',
      'Programming in Python',
      'Real and Complex Analysis',
      'Advanced Differential Equations and Applications',
      'Time Series Analysis and Forecasting',
      'Soft Computing',
    ],
  },

  fourth: {
    cse: [
      'Engineering Economics and Accountancy',
      'Artificial Intelligence',
      'Industrial Training',
      'Dataware Housing and Data Mining',
      'Information Security',
      'General Proficiency',
    ],
    ece: [
      'Control System',
      'Optical Communication Systems and Networks',
      'Engineering Economics and Accountancy',
      'Data Communication and Computer Networks',
    ],
    ee: [
      'Engineering Economics and Accountancy',
      'Modern Control Systems',
      'High Voltage Engineering',
      'Communication Systems',
    ],
    ce: [
      'Engineering Economics & Accountancy',
      'Design of Hydraulic Structures',
      'Prestressed Concrete',
      'Quantity Surveying',
    ],
    ch: [
      'Process Plant Design and Economics',
      'Petroleum Refining and Petrochemical Engineering',
      'Engineering Economics and Accountancy',
      'Industrial Safety and Hazard Management ',
    ],
    me: [
      'Operations Research',
      'Computer Aided Design',
      'Engineering Economics & Accountancy',
      'Computer Aided Manufacturing',
    ],
    ms: [
      'Thin Film Technology',
      'Corrosion Science and Engineering',
      'Engineering Economics and Accountancy',
      'Failure Analysis of Materials',
    ],
    ma: [
      'Engineering Economics and Accountancy',
      'Cryptography and Information Security',
      ' Artificial Intelligence',
      'Multivariate Statistical Analysis',
    ],
  },
};
