export const dataSubjects = [
  '',
  'Engineering Mathematics-I/Engineering Mathematics-II',
  'Computer Programming',
  'Engineering Graphics',
  'Engineering Physics',
  'Applied Mechanics',
  'Basic Electronics Engineering',
  'Communication Skills',
  'Engineering Workshop',
  'Engineering Chemistry',
  'Materials Science & Engineering',
  'Basic Electrical Engineering',
  'Engineering mathematics-III',
  'Object Oriented Programming',
  'Microprocessor and Interfacing',
  'Discrete Structures',
  'Digital Electronincs and Logic Design',
  'Organizational Behaviour',
  'Data Strutures',
  'Computer Organization and Architecture',
  'Operating System',
  'Theory of Computation',
  'Digital Electronics and Logic Design',
  'Analog Electronics',
  'Communication Theory',
  'Data Structures',
  'Engineering Mathematics-III',
  'Linear Integrated Circuits',
  'Analog Communucation Systems',
  'Electromagnetic Field Theory',
  'VLSI Technology',
  'Network Analysis and Synthesis',
  'Electrical and Elecrtonic Measurements',
  'Organizational Bhaviour',
  'Electrical Machines-I',
  'Microprocessor Architecture and Interfacing',
  'Power electronics',
  'Power System',
  'Determinate Structures',
  'Fluid Mechanics',
  'Engineering Geology and Rock Mechanics',
  'Surveying',
  'Indeterminate Structures',
  'Water Resource Engineering-I',
  'Soil Mechanics',
  'Building Materials and Construction',
  'Chemical Engineering Thermodynamics-I',
  'Chemical Process Calculations',
  'Mechanical Operation',
  'Heat Transfer',
  'Chemical Engineering Thermodynamics-II',
  'Industrial Pollution Abatement',
  'Chemical Technology',
  'Organization Behavior',
  'Kinetics of Machines',
  'Engineering Thermodynamics',
  'Fluid Mechanics and Machinery',
  'Metrology and Measurement',
  'Dynamics of Machines',
  'Heat and Mass Transfer',
  'Mechanics of Solids',
  'Industrial Engineering',
  'Organizational Behavior',
  'Phase Transformation',
  'Transport Phenomena',
  'Materials Thermodynamics and Kinetics',
  'Mechanical Behavior of Materials',
  'Heat Treatment',
  'Polymer Science and Technology',
  'Composite Materials',
  'Materials Processing Techniques',
  'Discrete Mathematics',
  'Stochastic Processes',
  'Computer Graphics',
  'Linear Algebra and Applications',
  'Statistical Methods',
  'Data Structure',
  'Analysis and Designs of Algorithms',
  'Database Management Systems',
  'Compiler Design',
  'Distributed Systems',
  'Software Engineering',
  'Digital Image Processing',
  'Computer Networks',
  'Microprocessor Arhitecture and Applications',
  'Digital Communication and Systems',
  'Digital Signal processing',
  'Microware Devices and Systems',
  'Microcontroller and Embedded Systems',
  'Wireless Communication',
  'VLSI Design Techniques',
  'Antenna and Wave propagation',
  'Protection and Switchgear',
  'Electrical Machines-II',
  'Signals and Systems',
  'Transducers and Signal Conditioning',
  'Control Engineering',
  'Power System Analysis',
  'Digital Signal Processing',
  'Electric Drives',
  'RCC Design',
  'Water Supply and Treatment',
  'Foundation Engineering',
  'Highway Engineering',
  'Steel Structure',
  'Water Resources Engineering-II',
  'Railways and Airports',
  'Waste Water Treatment and Management',
  'Mass Transfer-I',
  'Chemical Reaction Engineering-I',
  'Process Equipment Design-I',
  'Process Dynamics and Control',
  'Mass Transfer-II',
  'Chemical Reaction Engineering-II',
  'Process Equipment Design-II',
  'Process Modeling and Simulation',
  'Machine Design-I',
  'Manufacturing Science and Technology-I',
  'Thermal Power Engineering-I',
  'Refrigeration and Air Conditioning',
  'Machine Design-II',
  'Manufacturing Science and Technology-II',
  'Thermal Power Engineering-II',
  'Automobile Engineering',
  'Characterization of Materials',
  'Ceramics Science and Engineering',
  'Iron and Steel Making',
  'Metal working Science & Technology',
  'Non-Destructive Testing of Materials',
  'Tribology of Engineering Materials',
  'Non-Ferrous Extractive Metallurgy',
  'Computational Materials Science',
  'Operation Research',
  'Number Theory and Abstract Algebra',
  'Data Base Management Systems',
  'Programming in Python',
  'Real and Complex Analysis',
  'Advanced Differential Equations and Applications',
  'Time Series Analysis and Forecasting',
  'Soft Computing',
  'Engineering Economics and Accountancy',
  'Artificial Intelligence',
  'Industrial Training',
  'Dataware Housing and Data Mining',
  'Information Security',
  'General Proficiency',
  'Control System',
  'Optical Communication Systems and Networks',
  'Data Communication and Computer Networks',
  'Modern Control Systems',
  'High Voltage Engineering',
  'Communication Systems',
  'Engineering Economics & Accountancy',
  'Design of Hydraulic Structures',
  'Prestressed Concrete',
  'Quantity Surveying',
  'Process Plant Design and Economics',
  'Petroleum Refining and Petrochemical Engineering',
  'Industrial Safety and Hazard Management ',
  'Operations Research',
  'Computer Aided Design',
  'Computer Aided Manufacturing',
  'Thin Film Technology',
  'Corrosion Science and Engineering',
  'Failure Analysis of Materials',
  'Cryptography and Information Security',
  ' Artificial Intelligence',
  'Multivariate Statistical Analysis',
];
